services:
  app:
    build: .
    container_name: java17-h2-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:dbcupom
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
    volumes:
      - h2-data:/root
    restart: always

volumes:
  h2-data: